#!/usr/bin/env python3
"""Merge, validate, and render the full law catalog.

Reads:   data/catalog/ot-part*.json  (613 Torah commandments, thematic order)
         data/catalog/nt-norms.json  (New Testament enforceable norms)
Writes:  data/catalog/catalog.json   (merged, numbered — machine-readable)
         data/catalog/CATALOG.md     (grouped by Federal Code Title)
         data/csv/catalog.csv        (flat index)

Entry shape in the part files:
  [polarity P/N, title, citation, category, code_title, agency, status, summary]

The OT count must equal exactly 613 (the classical enumeration); the build
fails otherwise. Numbering is assigned here (USC-001..USC-613, NT-001..),
so parts can be edited freely.

Statuses:
  enforced   on the books and policed
  adapted    enforced in a modernized/renamed form
  deferred   affirmed and indefinitely postponed (the Jubilee pattern)
  abeyance   requires the Temple; held by the TRA in the Suspended Rites Register
  classified Title XII and the herem statutes
  omitted    never printed, never repealed — the suppressed verses
  counsel    'eschatological counsel, not civil statute' (CSC 1-02) — NT only
"""

import csv
import json
from collections import Counter
from pathlib import Path

PROJECT = Path(__file__).resolve().parent.parent
CAT = PROJECT / "data" / "catalog"

TITLES = {
    "I": "Title I — The Covenant",
    "II": "Title II — Worship & Devotion",
    "III": "Title III — Family Order",
    "IV": "Title IV — Persons & Violence",
    "V": "Title V — Servitude & Labor",
    "VI": "Title VI — Property & Restitution",
    "VII": "Title VII — Purity & Diet",
    "VIII": "Title VIII — Festivals & Calendar",
    "IX": "Title IX — Justice & Procedure",
    "X": "Title X — Revenue",
    "XI": "Title XI — Aliens & Strangers",
    "XII": "Title XII — War",
}
STATUSES = {"enforced", "adapted", "deferred", "abeyance", "classified", "omitted", "counsel"}
AGENCIES = {"POTC", "COO", "CC", "DOR", "DOW", "TFRS", "DFO", "DLJ", "BSO", "OIP",
            "SSC", "FPA", "BWM", "RA", "OSO", "CSC", "NDS", "MCD", "TRA", "AHS", "BRC"}


def load(path):
    rows = json.loads(path.read_text(encoding="utf-8"))
    out, errs = [], []
    for i, r in enumerate(rows):
        if len(r) != 8:
            errs.append(f"{path.name}[{i}]: wrong arity")
            continue
        pol, title, cit, cat, code_title, agency, status, summary = r
        if pol not in ("P", "N"):
            errs.append(f"{path.name}[{i}] {title!r}: polarity {pol!r}")
        if code_title not in TITLES:
            errs.append(f"{path.name}[{i}] {title!r}: code_title {code_title!r}")
        if agency not in AGENCIES:
            errs.append(f"{path.name}[{i}] {title!r}: agency {agency!r}")
        if status not in STATUSES:
            errs.append(f"{path.name}[{i}] {title!r}: status {status!r}")
        out.append({"polarity": pol, "title": title, "citation": cit,
                    "category": cat, "code_title": code_title,
                    "agency": agency, "status": status, "summary": summary})
    return out, errs


def main():
    errs = []
    ot = []
    for p in sorted(CAT.glob("ot-part*.json")):
        rows, e = load(p)
        ot += rows
        errs += e
    nt, e = load(CAT / "nt-norms.json")
    errs += e
    if errs:
        print("ERRORS:")
        for x in errs:
            print(" -", x)
        raise SystemExit(1)
    if len(ot) != 613:
        raise SystemExit(f"OT catalog has {len(ot)} entries; the enumeration must be exactly 613.")

    for i, r in enumerate(ot, 1):
        r["id"] = f"USC-{i:03d}"
        r["testament"] = "Old"
    for i, r in enumerate(nt, 1):
        r["id"] = f"NT-{i:03d}"
        r["testament"] = "New"
    allrows = ot + nt

    (CAT / "catalog.json").write_text(
        json.dumps({"ot_count": len(ot), "nt_count": len(nt), "laws": allrows},
                   indent=1, ensure_ascii=False), encoding="utf-8")

    # CSV
    (PROJECT / "data" / "csv").mkdir(parents=True, exist_ok=True)
    with open(PROJECT / "data" / "csv" / "catalog.csv", "w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        cols = ["id", "testament", "polarity", "title", "citation", "category",
                "code_title", "agency", "status", "summary"]
        w.writerow(cols)
        for r in allrows:
            w.writerow([r[c] for c in cols])

    # Markdown, grouped by Code Title
    sc = Counter(r["status"] for r in allrows)
    lines = [
        "# The Catalog of the Laws",
        "",
        f"**{len(ot)} commandments of the Torah** (the classical enumeration, thematic order)",
        f"and **{len(nt)} enforceable norms of the New Testament**, assigned to the",
        "twelve Titles of the Federal Code of the United States of Christ.",
        "",
        "Generated by `tools/build_catalog.py` from `data/catalog/*.json` — do not hand-edit.",
        "Deep extraction records (one file per law, full schema) live in `data/laws/`;",
        "entries marked *see deep record* link there.",
        "",
        "## Enforcement status legend",
        "",
        "| Status | Meaning | Count |",
        "|---|---|---|",
        "| enforced | on the books and policed | " + str(sc["enforced"]) + " |",
        "| adapted | enforced in modernized or renamed form | " + str(sc["adapted"]) + " |",
        "| deferred | affirmed and indefinitely postponed (the Jubilee pattern) | " + str(sc["deferred"]) + " |",
        "| abeyance | requires the Temple; held in the TRA's Suspended Rites Register | " + str(sc["abeyance"]) + " |",
        "| classified | Title XII and the herem statutes | " + str(sc["classified"]) + " |",
        "| omitted | never printed, never repealed — the suppressed verses | " + str(sc["omitted"]) + " |",
        "| counsel | 'eschatological counsel, not civil statute' (CSC 1-02) | " + str(sc["counsel"]) + " |",
        "",
        "*The gap between the first row and the last three is the regime's fingerprint.*",
        "",
    ]
    for tkey, tname in TITLES.items():
        rows = [r for r in allrows if r["code_title"] == tkey]
        if not rows:
            continue
        lines += [f"## {tname}", "",
                  f"{len(rows)} laws.", "",
                  "| # | ± | Law | Citation | Agency | Status | Summary |",
                  "|---|---|---|---|---|---|---|"]
        for r in rows:
            summary = r["summary"].replace("|", "\\|")
            lines.append(
                f"| {r['id']} | {r['polarity']} | **{r['title']}** | {r['citation']} "
                f"| {r['agency']} | {r['status']} | {summary} |")
        lines.append("")
    (CAT / "CATALOG.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"OK: {len(ot)} OT + {len(nt)} NT laws.")
    print("By status:", dict(sc.most_common()))
    print("By title:", {k: sum(1 for r in allrows if r['code_title'] == k) for k in TITLES})


if __name__ == "__main__":
    main()
